# Generated by Django 6.0 on 2025-12-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCajas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
