# Generated by Django 4.2.11 on 2025-12-10 15:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),                
                ('rut', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')])),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Plazo Indefinido'), ('fijo', 'Plazo Fijo')], max_length=20)),
                ('tipo_caja', models.CharField(choices=[('estandar', 'Estándar'), ('especial', 'Especial'), ('premium', 'Premium')], default='estandar', max_length=20)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('casablanca', 'Casa Blanca'), ('valparaiso_bif', 'Valparaíso Planta BIF'), ('valparaiso_bic', 'Valparaíso Planta BIC')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('retirado_por_tercero', models.BooleanField(default=False)),
                ('nombre_tercero', models.CharField(blank=True, max_length=200)),
                ('rut_tercero', models.CharField(blank=True, max_length=12)),
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiro', to='registroCajas.beneficiario')),
                ('confirmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('guardia', 'Guardia / Portería'), ('trabajador', 'Trabajador')], max_length=20)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')])),
                ('nombre_completo', models.CharField(max_length=200)),
                ('planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registroCajas.planta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('archivo_nomina', models.FileField(blank=True, null=True, upload_to='nominas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCajas.planta')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='registroCajas.campana'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroCajas.planta'),
        ),
        migrations.CreateModel(
            name='AutorizacionTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tercero', models.CharField(max_length=200)),
                ('rut_tercero', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')])),
                ('fecha_autorizada', models.DateField()),
                ('solo_una_vez', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='registroCajas.beneficiario')),
            ],
            options={
                'verbose_name': 'Autorización Tercero',
                'verbose_name_plural': 'Autorizaciones Terceros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AgendaRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendada', models.DateField()),
                ('confirmado_hoy', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='registroCajas.beneficiario')),
            ],
            options={
                'verbose_name': 'Agenda de Retiro',
                'verbose_name_plural': 'Agendas de Retiro',
                'ordering': ['fecha_agendada'],
            },
        ),
        migrations.CreateModel(
            name='DiaBloquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(choices=[('emergencia', 'Emergencia'), ('feriado', 'Feriado'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], default='emergencia', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_bloqueo', models.DateTimeField(auto_now_add=True)),
                ('bloqueado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to='registroCajas.campana')),
            ],
            options={
                'verbose_name': 'Día Bloqueado',
                'verbose_name_plural': 'Días Bloqueados',
                'ordering': ['fecha'],
                'unique_together': {('campana', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='beneficiario',
            unique_together={('campana', 'rut')},
        ),
    ]
