# Generated by Django 5.2.8 on 2025-12-17 13:07

from django.db import migrations, models
import random
import string


def generar_codigos_existentes(apps, schema_editor):
    """Genera códigos para retiros existentes"""
    Retiro = apps.get_model('registroCajas', 'Retiro')

    for retiro in Retiro.objects.all():
        # Prefijo según tipo de contrato
        prefijo = 'I' if retiro.beneficiario.tipo_contrato == 'indefinido' else 'F'

        # Usar día del mes de la fecha de retiro + aleatorio
        dia = retiro.fecha_hora.strftime('%d')
        aleatorio = ''.join(random.choices(string.digits + string.ascii_uppercase, k=3))
        codigo = f"{prefijo}-{dia}{aleatorio}"

        # Verificar que sea único
        while Retiro.objects.filter(codigo_caja=codigo).exists():
            aleatorio = ''.join(random.choices(string.digits + string.ascii_uppercase, k=3))
            codigo = f"{prefijo}-{dia}{aleatorio}"

        retiro.codigo_caja = codigo
        retiro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('registroCajas', '0001_initial'),
    ]

    operations = [
        # Primero agregar el campo sin unique
        migrations.AddField(
            model_name='retiro',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=7),
        ),
        # Generar códigos para registros existentes
        migrations.RunPython(generar_codigos_existentes, migrations.RunPython.noop),
        # Ahora hacer el campo único
        migrations.AlterField(
            model_name='retiro',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
