# Generated by Django 5.2.8 on 2025-12-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroCajas', '0002_retiro_codigo_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
