# Generated by Django 5.2.8 on 2025-12-17 13:42

from django.db import migrations, models
import re


def generar_codigos_beneficiarios(apps, schema_editor):
    """Genera códigos para beneficiarios existentes"""
    Beneficiario = apps.get_model('registroCajas', 'Beneficiario')
    Planta = apps.get_model('registroCajas', 'Planta')

    # Mapeo de códigos de planta
    def get_codigo_corto(codigo_planta):
        codigos = {
            'casablanca': 'CB',
            'valparaiso_bif': 'BIF',
            'valparaiso_bic': 'BIC',
        }
        return codigos.get(codigo_planta, 'XXX')

    # Agrupar beneficiarios por campaña y planta
    from collections import defaultdict
    beneficiarios_por_campana_planta = defaultdict(list)

    for beneficiario in Beneficiario.objects.all().order_by('id'):
        key = f"{beneficiario.campana_id}_{beneficiario.planta_id}"
        beneficiarios_por_campana_planta[key].append(beneficiario)

    # Generar códigos con correlativos
    for key, beneficiarios in beneficiarios_por_campana_planta.items():
        if not beneficiarios:
            continue

        # Usar el primer beneficiario para obtener datos de la campaña
        primer_beneficiario = beneficiarios[0]
        fecha_inicio = primer_beneficiario.campana.fecha_inicio
        dia = fecha_inicio.strftime('%d')
        mes = fecha_inicio.strftime('%m')

        # Obtener código de planta
        planta_obj = Planta.objects.get(id=primer_beneficiario.planta_id)
        planta_codigo = get_codigo_corto(planta_obj.codigo)

        # Generar códigos con correlativo
        correlativo = 1
        for beneficiario in beneficiarios:
            prefijo = 'I' if beneficiario.tipo_contrato == 'indefinido' else 'F'
            correlativo_str = str(correlativo).zfill(2)
            codigo = f"{prefijo}-{dia}{mes}{planta_codigo}{correlativo_str}"

            beneficiario.codigo_caja = codigo
            beneficiario.save()

            correlativo += 1


class Migration(migrations.Migration):

    dependencies = [
        ('registroCajas', '0003_alter_retiro_codigo_caja'),
    ]

    operations = [
        # Primero agregar el campo sin unique
        migrations.AddField(
            model_name='beneficiario',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=15),
        ),
        # Generar códigos para beneficiarios existentes
        migrations.RunPython(generar_codigos_beneficiarios, migrations.RunPython.noop),
        # Ahora hacer el campo único
        migrations.AlterField(
            model_name='beneficiario',
            name='codigo_caja',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
